<a href="https://colab.research.google.com/github/Dhyeonle9/deep-learning-practice/blob/main/231211_dl_10_window_datatset_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [11]:
# 0부터 9까지의 숫자로 구성된 데이터셋을 생성합니다.
dataset = tf.data.Dataset.range(10)

# 윈도우 함수를 사용하여 데이터를 윈도(창)로 분할합니다.
# 윈도 크기: 5, 이동 간격: 1, 남는 부분은 버립니다. (drop_remainder=True)
# 즉, 0~4, 1~5, 2~6, 3~7, 4~8, 5~9 5범위로
dataset = dataset.window(5, shift=1, drop_remainder=True)

# flat_map 함수를 사용하여 각 윈도를 배치로 변환합니다.
# 이렇게 하면 각 윈도를 텐서로 표현하지 않고 배치로 처리할 수 있습니다.
dataset = dataset.flat_map(lambda window: window.batch(5))

# 데이터셋의 각 윈도를 출력합니다.
for window in dataset:
    print(window.numpy())  # 각 윈도를 NumPy 배열로 변환하여 출력합니다.

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [8]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))

# 데이터셋의 각 윈도를 입력(x)과 출력(y)으로 나누고, 출력을 마지막 원소로 정의합니다.
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

# 데이터셋을 순회하며 입력(x)과 출력(y)을 출력합니다.
for x, y in dataset:
    print(x.numpy(), y.numpy())  # 각 윈도를 NumPy 배열로 변환하여 출력합니다.

[0 1 2 3] 4
[1 2 3 4] 5
[2 3 4 5] 6
[3 4 5 6] 7
[4 5 6 7] 8
[5 6 7 8] 9


In [12]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

# 데이터셋을 임의로 섞습니다. 버퍼 크기는 이 재배치를 얼마나 큰 범위에서 수행할지 결정합니다.
dataset = dataset.shuffle(buffer_size=10)
# 배치 크기를 2로 설정하고, 데이터를 미리 로드합니다.
dataset = dataset.batch(2).prefetch(1)

for x, y in dataset:
    print(x.numpy(), y.numpy())

[[4 5 6 7]
 [3 4 5 6]] [[8]
 [7]]
[[0 1 2 3]
 [5 6 7 8]] [[4]
 [9]]
[[1 2 3 4]
 [2 3 4 5]] [[5]
 [6]]
